# Это Version Catalog
# Файл, где в одном месте записаны версии всех библиотек и планинов проекта
# Модули ссылаются на них по имени, а сами номера версий не пишут
# Без этого файла версии пришлось бы прописывать в  build.gradle.kts каждого модуля

[versions]
kotlin = "2.4.20"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }